### ISSUE TITLE
Minified embedded Javascript fails

### ISSUE THREAD

**Issue by spapadim** [juancarlospaco/css-html-js-minify#21]
For the following HTML document:
  https://gist.github.com/84cdbef4ef081b963ac8
the minified output throws a Javascript error:
  `Uncaught SyntaxError: Unexpected token this`
whereas the original loads fine. Running v1.2.0 (off of pypi).

**Comment by spapadim** [comment]
I thought it's the // comments, but even changing both to /* .. */ does not help.  Oddly, if I beautify the minified code (eg with http://jsbeautifier.org/), then it works again.

**Comment by juancarlospaco** [comment]
We dont support Mixed Combined inline HTML with JS with CSS altogether,
separate the JS on a `*.js` file and separate the HTML on a `*.html` file,
and separate the CSS on a `*.css` file, which is kind of best practice anyways, 
even more with HTML5 "Imports", plus it helps the Caches.

Implementing that is complex due to the lifespan and variety of JS frameworks,
everything mixed with everything, it can be CoffeeScript or SASS or BabelJS ES7 or Jade or .............

If anyone want to add those features, Pull Requests are welcome...  :smile_cat:

**Comment by spapadim** [comment]
Thanks!!  In that case, an error (or at least a warning) stating this would be nice! :)

Agree on "best practice" comment, but just FYI: doing it this way because it's served from a microcontroller (eg see https://github.com/spapadim/ESPClock) and one HTTP request makes my life a *little* easier.  However, this particular microcontroller has a flash filesystem (not all do, though), so when I switch over to that, I'll *probably* separate the files (undecided, since it can't do concurrent requests or keep-alive, though).

**Comment by juancarlospaco** [comment]
You can try  HTML5 "Imports" if you dont have to support old browsers (works for me on Chromium, Firefox, Qupzilla), 
the cached files make the request once anyways, then its loaded from local cache, 
separating all stuff properly is better probably joining it on deploy, 
make sure you are serving with gZIP enabled, 
or get your statics from a CDN like RawGit (you have rawgit if you have github).
