### ISSUE TITLE
Would be nice as a module

### ISSUE THREAD

**Issue by Aeyoun** [juancarlospaco/css-html-js-minify#23]
It sure would be nice if you could let this be used as a Python module too.

**Comment by juancarlospaco** [comment]
But theres a lot of other (separated) libraries oriented to be used as Modules-only, when I started this Ive done it because theres nothing I can just `pip install` and minify whole project folders at once.

I have not checked recently if they still maintained like this one, but I am open to anything, if theres interest on it to be used as Module too, 

Pull Requests are Welcome, and its something to consider for future...   :smiley:

**Comment by Aeyoun** [comment]
He, I couldn’t find any recent Python modules that does CSS minification. There are a few for JavaScript, but only a handful for CSS and all of those were based on YUI compressor and has the same flaws.

**Comment by juancarlospaco** [comment]
:+1:

**Comment by juancarlospaco** [comment]
Fixed :grey_exclamation: Thanks...
