### ISSUE TITLE
Problem with output parsing javascript file

### ISSUE THREAD

**Issue by blasterspike** [juancarlospaco/css-html-js-minify#30]
Hi,
when parsing the javascript file inside the zip attached, at the beginning of the output file I find
```javascript
;;
```
so the output starts with
```javascript
;;MooTools.More=
```

This file is included in Joomla 3.4.8 in media/system/js/mootools-more.js

Tested with:
css-html-js-minify.py 1.2.2
Python 2.7.11

[mootools-more.zip](https://github.com/juancarlospaco/css-html-js-minify/files/145631/mootools-more.zip)

**Comment by juancarlospaco** [comment]
We will be deprecating 2.x support as soon as possible, since Unicode problems it brings, 
and its way out of scope of this project monkey patch that to workaround them, 
and we dont have the manpower to do it even if we wanted to...

Switching to 3.x is recommended, since is available on all Linux and Windows OS.

We will take a look anyways...
