### ISSUE TITLE
Compatibility with Python 2.7

### ISSUE THREAD

**Issue by borjamarcos** [juancarlospaco/css-html-js-minify#44]
do you have in mind this compatibility?

Actually, there is more people using this version than 3.5 and should be fine to have this possibility.

**Comment by juancarlospaco** [comment]
Nope.

You can use any version Previous to this version: https://github.com/juancarlospaco/css-html-js-minify/commits/master?after=VF23zkcDg8mwbpCyCewLJ6VJfeYrMzQ%3D

We are ending 2016, on 2018 all Apps should be migrating to Python3, thats less than a year,
from 2018 to 2020 Python2 will be deprecated and abandoned for ever, not even basic patches.

You can still use Python2 on your App, and run this App from a Virtualenv Python3.

**Comment by rcarmo** [comment]
This feels a little extreme, considering that there are plenty of uses for this in Python2/Pypy land (where we need to run Python 2 for compatibility and performance reasons) and that it is possible to have a smoother transition.

So I'd just like to point out that even using pyenv, installing and switching to Python3 just for this is a mess (I've tried using the Alpine Python 3.5 Docker images I maintain, too, but that is also another level of unnecessary complexity), so I've started resorting to other tools.

Advocating Python 3 is good, but I'd rather you'd done it differently, especially since the 2018 cut-off date is just not going to happen in traditional IT.

**Comment by juancarlospaco** [comment]
We used to have a red blinking bold warning about migrating to python3 almost a year before...

**Comment by rcarmo** [comment]
I still come across machines running 2.4. Not joking.

**Comment by mverleg** [comment]
I'd say this project is not responsible for getting people to update their Python versions. But then, neither is it required to support outdated software.

So I'd suggest that if someone wants to put in the effort to add compatibility, it'd be a nice addition. Otherwise, too bad.

**Comment by rcarmo** [comment]
Well, I'm just going to leave this here, then.

https://semaphoreci.com/blog/2016/11/11/python-versions-used-in-commercial-projects-2016-edition.html

Regardless, I'm using jsmin and cssmin in 2.7 with adequate (if not stellar) results. Will see if there's something I can do about retro-patching this when I have time.

**Comment by juancarlospaco** [comment]
No Commercial project has ever take care of helping us at all.

But I know Commercial projects often uses very very old unpatched software internally...

**Comment by juancarlospaco** [comment]
Closing this for now...

As said on https://github.com/juancarlospaco/css-html-js-minify/issues/44#issuecomment-258958483 and https://github.com/juancarlospaco/css-html-js-minify/issues/44#issuecomment-256041338

Feel free to send pull requests for 2.x
